# Generated by Django 5.2.6 on 2025-10-29 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioBase',
            fields=[
                ('id_ejercicio', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('grupo_muscular', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], default=('Lunes', 'Lunes'), max_length=10)),
                ('descripcion', models.CharField(max_length=250)),
                ('objetivo', models.CharField(max_length=250)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sensaciones', models.CharField(max_length=250)),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_tracker.rutina')),
            ],
        ),
    ]
