# Generated by Django 5.2.6 on 2025-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0002_ejerciciobase_alter_usuario_email_rutina_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciobase',
            name='id_ejercicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
